services:
  app:
    container_name: films
    build:
      context: .
    depends_on:
      - postgres
    environment:
      - JWT_SECRET_KEY=
      - TEST_CONFIG_PATH=
      - CONFIG_PATH=
    ports:
      - '8080:8080'
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB='
      - 'POSTGRES_PASSWORD='
      - 'POSTGRES_USER='
    ports:
      - '5432'
